title: yunfuwu
#email: 
description: >- 
  Mainly aim at learning and deep learning.
author: freedo
avatar: /logo.png
baseurl: / 
url: "http://yunfuwu.net"
#twitter_username: 
#github_username:  

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 10

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
